language: node_js
node_js: 12
cache: npm

branches:
  except:
  - dev

before_script:
  - npm install -g hexo

script:
  - hexo g
  - mkdir ./public-git
  - cd ./public-git
  - git init
  - git config --global push.default matching
  - git config --global user.email "${GitHubEMail}"
  - git config --global user.name "${GitHubUser}"
  - git remote add origin https://${GitHubKEY}@github.com/${GitHubUser}/Rachel-s-Blog.git
  - git pull origin gh-pages
  - rm -rf ./*
  - cp -rf ../public/* ./
  - git stage --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force origin HEAD:gh-pages
