Menu:
  Home: /
  Archives: /archives/
  RSS: /atom.xml
  About: //me.stfw.info
  Search: true
  
Site:
  Title: Rachel
  Motto: Where Dreams Converge

CopyRight: 
  Author: Rachel030219
  License: CC BY-NC-SA 3.0

Tip:
  Alipay: 
  Wechat: /img/WeChat.png

Comment:
  Id: ${ClientID}
  Secret: ${ClientSecrets}
  Repo: Rachel-s-Blog
  Owner: Rachel030219