Menu:
  Home: /
  Archives: /archives/
  RSS: /atom.xml
  About: //rachelt.one
  Links: //rachelt.one
  Search: true
  
Site:
  Title: Rachel
  Motto: Where Dreams Converge

CopyRight: 
  Author: Rachel030219
  License: CC BY-NC-SA 3.0

Comment:
  Repo: Rachel-s-Blog
  Owner: Rachel030219
  Secret: ${COMMENT_SECRET}